### PR TITLE
The enhancement has been made

### PR DESCRIPTION
**Pull request by nahiyanbhuiyan2001**
Check out the enhancement and let me know.

thanks,
Nahiyan Bhuiyan

### CODE REVIEW

**Comment by jjj4671** [comment]
let me check and see if i like it

**Comment by nahiyanbhuiyan2001** [comment]
Ok. It was a simple yet cool touch.

**Comment by jjj4671** [comment]
oh, I like it! i didn't know such a small change could do something so nice

**Comment by nahiyanbhuiyan2001** [comment]
Next time, I will be changing the border colors if possible. For now, its a test run!

**Comment by jjj4671** [comment]
sounds good!

**Pull request merged**
